[tool.black]
line-length = 79
target-version = ['py310']  
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 79
exclude = '''
    .git,
    __pycache__,
    build,
    dist
'''

